local opt = { noremap = true }
local telescope = require("telescope")
telescope.setup({})
vim.api.nvim_set_keymap("n", "<leader><tab>", ":lua require('telescope.builtin').find_files()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fg", ":lua require('telescope.builtin').live_grep()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fb", ":lua require('telescope.builtin').buffers()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fh", ":lua require('telescope.builtin').help_tags()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fc", ":lua require('telescope.builtin').commands()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fm", ":lua require('telescope.builtin').marks()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fr", ":lua require('telescope.builtin').registers()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>ft", ":lua require('telescope.builtin').tags()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fT", ":lua require('telescope.builtin').tags{ only_current_buffer = true }<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>f/", ":lua require('telescope.builtin').current_buffer_fuzzy_find()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fF", ":lua require('telescope.builtin').file_browser()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fk", ":lua require('telescope.builtin').keymaps()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fgf", ":lua require('telescope.builtin').git_files()<CR>", opt)
vim.api.nvim_set_keymap("n", "<leader>fgc", ":lua require('telescope.builtin').git_commits()<CR>", opt)
